version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - echo Building the Node code...
      - cd $CODEBUILD_SRC_DIR/
      - npm install
      - npm run build
artifacts:
  files:
    - dist*/**
  discard-paths: yes