version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing dependencies...
      - cd $CODEBUILD_SRC_DIR/
      - npm install
  build:
    commands:
      - echo Building the Node code...
      - cd $CODEBUILD_SRC_DIR/
      - npm run webpack-dev
      - npm run copy-demo
artifacts:
  files:
    - dist/*/**