version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    pre_build:
      commands:
        - echo Pre Build
        - cd $CODEBUILD_SRC_DIR/
        - npm run build
  build:
    commands:
      - echo Building the Node code...
      - cd $CODEBUILD_SRC_DIR/
      - npm run build
artifacts:
  files:
    - dist*/**